{
 "title": "Transcendence Global overview",
 "description": "Vue d'ensemble de la sante du systeme et des performances. Inclut le monitoring de l'infra (Node Exporter) et les indicateurs cles du backend Node.js (Methode RED : Trafic, Erreurs, Latence).",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Logs application",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "100" }, "type": "logs" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Erreurs serveur (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(transcendence_http_requests_total{status_code=~\"5..\"}[2m]))",
     "legendFormat": "Number of ERR 5xx"
    }
   ]
  },
  {
   "title": "Latence par route",
   "type": "timeseries",
   "description": "Temps de reponse moyen du serveur, groupe par endpoinr",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (route, method) (rate(transcendence_http_request_duration_seconds_sum[2m])) / sum by (route, method) (rate(transcendence_http_request_duration_seconds_count[2m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Trafic Global",
   "type": "timeseries",
   "description": "Request per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(transcendence_http_requests_total[2m]))",
     "legendFormat": "RPS"
    }
   ]
  }
 ]
}