{
 "title": "Transcendence Global overview",
 "description": "Vue d'ensemble de la sante du systeme et des performances. Inclut le monitoring de l'infra (Node Exporter) et les indicateurs cles du backend Node.js (Methode RED : Trafic, Erreurs, Latence).",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Database (sqlite) & storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Espace disque libre",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Ecriture disque (database I/O)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total[2m]))",
     "legendFormat": "Vitesse d'ecriture"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs application",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Erreurs serveur (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(transcendence_http_requests_total{status_code=~\"5..\"}[2m]))",
     "legendFormat": "Number of ERR 5xx"
    }
   ]
  },
  {
   "title": "Latence par route",
   "type": "timeseries",
   "description": "Temps de reponse moyen du serveur, groupe par endpoinr",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (route, method) (rate(transcendence_http_request_duration_seconds_sum[2m])) / sum by (route, method) (rate(transcendence_http_request_duration_seconds_count[2m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Trafic Global",
   "type": "timeseries",
   "description": "Request per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(transcendence_http_requests_total[2m]))",
     "legendFormat": "RPS"
    }
   ]
  }
 ]
}